package com.sws.model;

// Generated 2017-11-3 15:11:24 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import com.gk.extend.hibernate.entity.BaseEntity;

/**
 * Hospital generated by hbm2java
 */
public class Hospital extends BaseEntity implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5400229543787483975L;
	private Integer number;
	private String name;
	private String address;
	private String remark;
	private Date createTime;

	public Hospital() {
	}

	public Hospital(Integer number, String name, String address,
			String remark, Date createTime) {
		this.number = number;
		this.name = name;
		this.address = address;
		this.remark = remark;
		this.createTime = createTime;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
