package com.sws.model;

import java.io.Serializable;
import java.util.Date;

import com.gk.extend.hibernate.entity.BaseEntity;

/**
 * ManualRecord generated by hbm2java
 * 人工录入的信息
 * @author wwg
 */
public class ManualRecord extends BaseEntity implements Serializable {

	/**
	 * 实例化
	 */
	private static final long serialVersionUID = -1814071135390164646L;
	
	/*
	 * 部门Id
	 */
	private Long departId;
	
	/*
	 * 被观察人姓名
	 */
	private String observerName;
	
	/*
	 * 手卫生时间
	 */
	private Date time;
	
	/*
	 * 洗手时机（1：接触病患前:2：接触病患后:3：无菌操作前:4：接触体液后:5：接触患者环境后）
	 */
	private Short occassion;
	
	/*
	 * 洗手方式（1表示水洗；2表示洗消）
	 */
	private Short way;
	
	/*
	 * 是否正确手卫生（1表示正确，0表示不正确）
	 */
	private Short isRight;
	
	/*
	 * 角色Id
	 */
	private Long roleId;
	
	/*
	 * 被观察人工号
	 */
	private String observerNumber;
	
	/*
	 * 是否洗手（1表示洗手，0表示未洗手）
	 */
	private Short isWashHand;

	public ManualRecord() {
	}

	public ManualRecord(Long departId, String observerName, Date time,
			Short occassion, Short way, Short isRight, Long roleId,
			String observerNumber, Short isWashHand) {
		this.departId = departId;
		this.observerName = observerName;
		this.time = time;
		this.occassion = occassion;
		this.way = way;
		this.isRight = isRight;
		this.roleId = roleId;
		this.observerNumber = observerNumber;
		this.isWashHand = isWashHand;
	}

	public Long getDepartId() {
		return this.departId;
	}

	public void setDepartId(Long departId) {
		this.departId = departId;
	}

	public String getObserverName() {
		return this.observerName;
	}

	public void setObserverName(String observerName) {
		this.observerName = observerName;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Short getOccassion() {
		return this.occassion;
	}

	public void setOccassion(Short occassion) {
		this.occassion = occassion;
	}

	public Short getWay() {
		return this.way;
	}

	public void setWay(Short way) {
		this.way = way;
	}

	public Short getIsRight() {
		return this.isRight;
	}

	public void setIsRight(Short isRight) {
		this.isRight = isRight;
	}

	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public String getObserverNumber() {
		return this.observerNumber;
	}

	public void setObserverNumber(String observerNumber) {
		this.observerNumber = observerNumber;
	}

	public Short getIsWashHand() {
		return isWashHand;
	}

	public void setIsWashHand(Short isWashHand) {
		this.isWashHand = isWashHand;
	}

	@Override
	public String toString() {
		return "ManualRecord [departId=" + departId + ", observerName="
				+ observerName + ", time=" + time + ", occassion=" + occassion
				+ ", way=" + way + ", isRight=" + isRight + ", roleId="
				+ roleId + ", observerNumber=" + observerNumber
				+ ", isWashHand=" + isWashHand + "]";
	}

}
